# Generated by Django 5.2.4 on 2025-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
